#ifndef __vehicle_edit_dialog__
#define __vehicle_edit_dialog__

/**
@file
Subclass of VehicleEditDialog, which is generated by wxFormBuilder.
*/

#include "../interface/i_vehicle_edit_dialog.h"
#include "database/vehicle.hpp"

//// end generated include

/** Implementing VehicleEditDialog */
class CVehicleEditDialog : public IVehicleEditDialog
{
private:
	SVehicle* m_representedVehicle;
protected:
	// Handlers for VehicleEditDialog events.
	void OnEditButtonClicked(wxCommandEvent& event);
	void OnCloseButtonClicked(wxCommandEvent& event);
public:
	/** Constructor */
	CVehicleEditDialog(SVehicle* vehicle, wxWindow* parent);
	//// end generated class members
};

#endif // __vehicle_edit_dialog__
