#ifndef __vehicle_edit_dialog__
#define __vehicle_edit_dialog__

/**
@file
Subclass of VehicleEditDialog, which is generated by wxFormBuilder.
*/

#include "../interface/i_vehicle_edit_dialog.h"
#include "database/vehicle.hpp"

//// end generated include

/** Implementing VehicleEditDialog */
class EVehicleEditDialog : public VehicleEditDialog
{
private:
	SVehicle* m_representedVehicle;
protected:
	// Handlers for VehicleEditDialog events.
	void OnEditButtonClicked(wxCommandEvent& event);
	void OnCloseButtonClicked(wxCommandEvent& event);
public:
	/** Constructor */
	EVehicleEditDialog(SVehicle* Vehicle, wxWindow* parent);
	//// end generated class members
private:
	void populateVehicleTypeChoice();
	void populateFuelChoice();
	void populateTransmissionChoice();
	void populateWheelDriveChoice();
	void populateDoorQuantityChoice();
};

#endif // __vehicle_edit_dialog__
